from __future__ import annotations

import re
from html.parser import HTMLParser
from pathlib import Path

from pypdf import PdfReader


ROOT = Path(__file__).resolve().parent


class HTMLChecker(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.stack: list[str] = []
        self.errors: list[str] = []

    def handle_starttag(self, tag, attrs):
        if tag not in {"meta", "link", "img", "br", "hr", "input"}:
            self.stack.append(tag)

    def handle_endtag(self, tag):
        if tag in {"meta", "link", "img", "br", "hr", "input"}:
            return
        if not self.stack or self.stack[-1] != tag:
            self.errors.append(f"mismatched closing tag: {tag}")
            return
        self.stack.pop()


def balanced_tex(tex: str) -> tuple[bool, str]:
    # Ignore escaped braces and count structural braces.
    depth = 0
    for idx, ch in enumerate(tex):
        if ch != "{" or (idx > 0 and tex[idx - 1] == "\\"):
            if ch == "}" and not (idx > 0 and tex[idx - 1] == "\\"):
                depth -= 1
                if depth < 0:
                    return False, f"closing brace before opening at offset {idx}"
            continue
        depth += 1
    if depth:
        return False, f"{depth} unmatched opening braces"
    return True, "balanced"


def main() -> None:
    md = (ROOT / "manuscript.md").read_text(encoding="utf-8")
    html_text = (ROOT / "manuscript.html").read_text(encoding="utf-8")
    tex_text = (ROOT / "main.tex").read_text(encoding="utf-8")
    pdf = ROOT / "TAG_KG_journal_extension.pdf"
    reader = PdfReader(str(pdf))
    pdf_text = "\n".join((page.extract_text() or "") for page in reader.pages)

    checks: list[tuple[str, bool, str]] = []
    body = md.split("## References", 1)[0]
    words = len(re.findall(r"\b[\w'-]+\b", body))
    checks.append(("article word count", words >= 8000, str(words)))

    hp = HTMLChecker()
    hp.feed(html_text)
    checks.append(("HTML nesting", not hp.errors and not hp.stack, str(hp.errors or hp.stack)))

    tex_ok, tex_msg = balanced_tex(tex_text)
    checks.append(("LaTeX brace balance", tex_ok, tex_msg))
    checks.append(("LaTeX document pair", tex_text.count(r"\begin{document}") == 1 and tex_text.count(r"\end{document}") == 1, "document environment"))
    checks.append(("LaTeX no raw TeX delimiters", r"\textbackslash{}(" not in tex_text, "inline math delimiters converted"))
    checks.append(("LaTeX display equations", tex_text.count(r"\begin{equation}") >= 7, "equation environments generated"))
    checks.append(("No formula-as-code blocks", r"\begin{center}\texttt{" not in tex_text, "formulas are mathematical environments"))

    for fig in ["fig1_architecture.svg", "fig2_protocol.svg", "fig3_risk_coverage.svg", "fig4_performance.svg", "fig5_audit.svg"]:
        checks.append((f"figure exists: {fig}", (ROOT / "figures" / fig).exists(), ""))

    checks.append(("PDF pages", len(reader.pages) >= 15, str(len(reader.pages))))
    for value in [".844", ".701", ".030", "3,100", "11,110", "Table 5", "Table 10"]:
        present = value in md and value in html_text and value in tex_text and value in pdf_text
        checks.append((f"headline value {value}", present, "present in md/html/tex/pdf"))

    result = ["# Package validation report", "", "Generated by `validate_package.py`.", ""]
    for name, ok, detail in checks:
        result.append(f"- [{'PASS' if ok else 'FAIL'}] {name}: {detail}")
    result.append("")
    result.append(f"PDF page count: {len(reader.pages)}")
    result.append(f"PDF extracted characters: {len(pdf_text)}")
    result.append(f"Article body word count: {words}")
    (ROOT / "validation_report.md").write_text("\n".join(result) + "\n", encoding="utf-8")
    print("\n".join(result))
    if not all(ok for _, ok, _ in checks):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
